/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.service.GitService;

public class App {
	
	public String getGreeting() {
		return "Hello World, I am a Gradle project...";
	}

    public static void main(String[] args) {
				
		String publicKeyPath = "pubkey_path.pem";
		String privateKeyPath = "privkey_path.pem";
		
		
		// Create Git Service object
		GitService gitService = new GitService("git@github.com:userName/repoName.git", "/path/to/local/gitDir");
		
		gitService.createSshService(publicKeyPath, privateKeyPath);
		
		// Pick which method you would like to use from GitService --> cloneRepository() OR addCommitPush()
		//gitService.cloneRepository();
		gitService.addCommitPush();

		gitService.deleteConfigFile();
		
		// Before the end of the main method, close out of SSH service
		gitService.stopSshService();
	}
}