/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
    
    // Eclipse JGit dependency
    implementation("org.eclipse.jgit:org.eclipse.jgit:6.7.0.202309050840-r")

    // Uncomment if using JSch for SSH (adjust version if necessary)
    // implementation("org.eclipse.jgit:org.eclipse.jgit.ssh.jsch:6.9.0.202403050737-r")

    // JGit SSH Apache
    implementation("org.eclipse.jgit:org.eclipse.jgit.ssh.apache:6.10.0.202406032230-r")

    // SLF4J for logging
    implementation("org.slf4j:slf4j-api:2.0.7")
    implementation("org.slf4j:slf4j-simple:2.0.7")

    // Commons IO
    implementation("commons-io:commons-io:2.16.1")

    // Apache SSHD Core
    implementation("org.apache.sshd:sshd-core:2.10.0")

    // JGit SSH Apache (repeat avoided)
    implementation("org.eclipse.jgit:org.eclipse.jgit.ssh.apache:6.7.0.202309050840-r")
    
    // https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk18on
	implementation("org.bouncycastle:bcprov-jdk18on:1.78.1")
	
	// https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-jdk15on
	implementation("org.bouncycastle:bcpkix-jdk15on:1.70")
	

    
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
